# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_user_completed_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600, verbose_name=b'Escribe una breve presentaci\xc3\xb3n sobre tu experiencia laboral...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biographic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Profile')),
                ('category', models.CharField(max_length=100, verbose_name=b'Categor\xc3\xada')),
                ('complete', models.IntegerField(default=0)),
                ('marital_status', models.IntegerField(choices=[(1, b'Soltera/o'), (2, b'Casada/o'), (3, b'Divorsiada/o'), (4, b'Viuda/o')], verbose_name=b'Estado Civil')),
                ('dni', models.IntegerField(verbose_name=b'DNI')),
                ('date_of_birth', models.DateField(verbose_name=b'Fecha de nacimiento')),
                ('postal_code', models.CharField(max_length=20, verbose_name=b'C\xc3\xb3digo Postal')),
                ('driver_license', models.IntegerField(choices=[(99, b'Ning\xc3\xbana'), (1, b'Auto'), (2, b'Motocicleta'), (3, b'Profesional')], null=True, verbose_name=b'Licencia de conducir')),
                ('own_vehicle', models.BooleanField(choices=[(True, b'Si'), (False, b'No')], default=False, verbose_name=b'\xc2\xbfPos\xc3\xa9e veh\xc3\xadculo propio?')),
                ('has_disability', models.BooleanField(default=False, verbose_name=b'\xc2\xbfPosee alg\xc3\xban tipo de discapacidad?')),
                ('country_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name=b'Nacionalidad')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name=b'Empresa')),
                ('start_date', models.DateField(verbose_name=b'Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'Fecha de finalizaci\xc3\xb3n')),
                ('is_current', models.BooleanField(default=False, verbose_name=b'Al presente')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n de responsabilidades y logros')),
                ('staff_charge', models.IntegerField(blank=True, choices=[(b'1', b'Sin personal a cargo'), (b'2', b'1 a 5'), (b'3', b'6 a 10'), (b'4', b'11 a 20'), (b'5', b'21 a 50'), (b'6', b'51 a 100'), (b'7', b'M\xc3\xa1s de 100')], null=True, verbose_name=b'Personal a cargo')),
                ('budget', models.BooleanField(choices=[(True, b'Si'), (False, b'No')], default=False, verbose_name=b'Presupuesto anual propio')),
                ('currency', models.CharField(choices=[(b'USD', b'D\xc3\xb3lar estadounidense'), (b'ARS', b'Peso argentino')], max_length=5, verbose_name=b'Moneda')),
                ('salary', models.FloatField(verbose_name=b'Sueldo')),
                ('show_salary', models.BooleanField(default=False, verbose_name=b'Mostrar Sueldo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Area', verbose_name=b'Area')),
                ('branch_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.BranchActivity', verbose_name=b'Ramo o actividad')),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.Hierarchy', verbose_name=b'Jerarquia')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.Position', verbose_name=b'Puesto')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.SubArea', verbose_name=b'Sub\xc3\xa1rea')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Direccion de correo electr\xf3nico')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel\xe9fono de contacto')),
                ('type', models.IntegerField(choices=[(1, 'Compa\xf1ero de trabajo'), (2, 'Estaba a su cargo'), (3, 'Era mi jefe'), (4, 'Estaba a mi cargo'), (99, b'Otro')], verbose_name='Relaci\xf3n laboral')),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='postulant.ProfessionalExperience')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
                ('description', models.CharField(max_length=300, verbose_name=b'Descripci\xc3\xb3n')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
                ('description', models.CharField(max_length=300, verbose_name=b'Descripci\xc3\xb3n')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.TitleRole', verbose_name=b'Titulo'),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL),
        ),
    ]
