# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0002_postulantavatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='branch_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.BranchActivity', verbose_name=b'Ramo o actividad'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='hierarchy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Hierarchy', verbose_name=b'Jerarquia'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Position', verbose_name=b'Puesto'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.TitleRole', verbose_name=b'Titulo'),
        ),
        migrations.DeleteModel(
            name='BranchActivity',
        ),
        migrations.DeleteModel(
            name='Hierarchy',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='TitleRole',
        ),
    ]
