# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0015_load_data'),
        ('postulant', '0003_auto_20161025_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulantRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(to='jobs.Role', verbose_name='Roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulant_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
