# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0004_postulantroles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulantavatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostulantAvatar',
        ),
    ]
