# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import postulant.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postulant', '0005_auto_20161124_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulantAttachCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('attach', models.FileField(upload_to=postulant.helpers.get_attachcv_directory, verbose_name='CV Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulant_attachcv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
