# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0007_auto_20170215_0057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postulantattachcv',
            unique_together=set([('user', 'name')]),
        ),
    ]
