# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_favoritejob'),
        ('postulant', '0009_professionalexperience_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Role', verbose_name=b'\xc3\x9altimo rol'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='company_address',
            field=models.CharField(max_length=100, verbose_name=b'Direcci\xc3\xb3n de la Empresa'),
        ),
    ]
