# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0010_auto_20190114_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.TitleRole', verbose_name=b'Titulo'),
        ),
    ]
