# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0012_auto_20190115_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='work_type',
            field=models.CharField(choices=[(b'Efectivo', b'Efectivo'), (b'Freelance', b'Freelance'), (b'Indiferente', b'Indiferente'), (b'Pasantia', b'Pasantia'), (b'PlazoFijo', b'Plazo Fijo'), (b'PorTemporadas', b'Por Temporadas'), (b'Temporal', b'Temporal')], default=b'Efectivo', max_length=30, verbose_name=b'Tipo de trabajo'),
        ),
    ]
