# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0013_professionalexperience_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='video_cv',
            field=models.FileField(null=True, upload_to=b'videos/', verbose_name=b'Video CV'),
        ),
    ]
