# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.Job'),
        ),
    ]
