# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_branchactivity_hierarchy_position_role_sector_titlerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branch_activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.BranchActivity', verbose_name='Ramo o actividad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='hierarchy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.Hierarchy', verbose_name='Jerarquia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.Position', verbose_name='Puesto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.TitleRole', verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='T\xedtulo del aviso'),
        ),
    ]
