# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 03:35
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20161025_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=('name',), unique=True, verbose_name='slug'),
        ),
    ]
