# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20161027_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
