# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_usercertification'),
        ('jobs', '0009_delete_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusive', models.BooleanField(default=True, verbose_name='Es excluyente')),
                ('level', models.IntegerField(choices=[(1, 'Primario'), (2, 'Secundario'), (4, 'Preparatoria'), (8, 'Terciario'), (16, 'Curso / Capacitaci\xf3n')], verbose_name='Niv\xe9l de educaci\xf3n m\xednimo')),
                ('finished', models.BooleanField(default=False, verbose_name='Terminado')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_requirements', to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusive', models.BooleanField(default=True, verbose_name='Es excluyente')),
                ('level', models.IntegerField(verbose_name='Niv\xe9l m\xednimo')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_requirements', to='jobs.Job')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Language', verbose_name='Lenguaje')),
            ],
        ),
    ]
