# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_educationrequirement_languagerequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrequirement',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_requirement', to='jobs.Job'),
        ),
    ]
