# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20161028_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Descripci\xc3\xb3n')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=(b'name',), unique=True, verbose_name=b'slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Descripci\xc3\xb3n')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=(b'name',), unique=True, verbose_name=b'slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subtechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtechnologies', to='jobs.Technology'),
        ),
    ]
