# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20161028_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtechnology',
            options={'verbose_name': 'Subtechnology', 'verbose_name_plural': 'Subtechnologies'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
