# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='roles',
            field=models.ManyToManyField(to='jobs.Role', verbose_name='Roles'),
        ),
    ]
