# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_question_questionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(20, 'Suspendido'), (30, 'Baneado'), (99, 'Borrador'), (0, 'Pendiente'), (1, 'Habilitado')], default=99),
        ),
    ]
