# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20161111_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('can_moderate', 'can_moderate'),)},
        ),
        migrations.AlterModelOptions(
            name='jobmoderationhistory',
            options={'ordering': ('-action_date',)},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(20, 'Publicado'), (10, 'Pendiente'), (99, 'Borrador'), (50, 'Rechazado'), (40, 'Baneado'), (30, 'Suspendido')], default=10),
        ),
        migrations.AlterField(
            model_name='jobmoderationhistory',
            name='new_status',
            field=models.IntegerField(choices=[(20, 'Publicado'), (10, 'Pendiente'), (99, 'Borrador'), (50, 'Rechazado'), (40, 'Baneado'), (30, 'Suspendido')], default=99, verbose_name='Cambiado a'),
        ),
        migrations.AlterField(
            model_name='jobmoderationhistory',
            name='old_status',
            field=models.IntegerField(choices=[(20, 'Publicado'), (10, 'Pendiente'), (99, 'Borrador'), (50, 'Rechazado'), (40, 'Baneado'), (30, 'Suspendido')], default=99, verbose_name='Cambiado de'),
        ),
    ]
