# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20161115_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobForModeration',
            fields=[
            ],
            options={
                'ordering': ('updated', 'created'),
                'verbose_name': 'Job for moderation',
                'proxy': True,
                'verbose_name_plural': 'Jobs for moderation',
            },
            bases=('jobs.job',),
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('can_moderate', 'Can moderate jobs'),)},
        ),
    ]
