# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20161116_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Fue moderado'),
        ),
    ]
