# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20161204_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostulation',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Le\xedda'),
        ),
    ]
