# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_jobpostulation_read'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobpostulation',
            unique_together=set([('job', 'user')]),
        ),
    ]
