# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20161207_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='postulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionsanswers', to='jobs.JobPostulation'),
        ),
    ]
