# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20170131_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region', verbose_name='Provincia'),
        ),
    ]
