# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_jobpostulationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostulation',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
    ]
