# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_jobpostulation_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='confidential',
            field=models.BooleanField(default=False, verbose_name='Confidencial'),
        ),
    ]
