# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_job_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contrataci\xf3n'),
        ),
        migrations.AddField(
            model_name='job',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicaci\xf3n'),
        ),
        migrations.AddField(
            model_name='job',
            name='residence_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Rango de residencia'),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de vacantes'),
        ),
        migrations.AddField(
            model_name='job',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
