# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20170513_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='residence_range_exclusive',
            field=models.BooleanField(default=False, verbose_name='Es excluyente'),
        ),
    ]
