# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_auto_20170514_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirement_driver_license',
            field=models.BooleanField(default=False, verbose_name='Licencia de conducir'),
        ),
    ]
