# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-23 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_auto_20170514_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contrataci\xf3n'),
        ),
        migrations.AlterField(
            model_name='job',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicaci\xf3n'),
        ),
    ]
