# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_auto_20170523_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contrataci\xf3n'),
        ),
        migrations.AlterField(
            model_name='job',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicaci\xf3n'),
        ),
        migrations.AddField(
            model_name='job',
            name='send_gratitude_by_mail',
            field=models.BooleanField(default=False, verbose_name='Enviar email de agradecimiento al postularse'),
        ),
    ]
