# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_favoritejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='similar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job', verbose_name='Aviso similar'),
        ),
    ]
