# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (99, 'Otro')], verbose_name='G\xe9nero'),
        ),
    ]
