# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160913_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_profile_update',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 18, 23, 54, 38, 409074, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
