# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161111_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede entrar en este sitio de administraci\xf3n.'),
        ),
    ]
