# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170131_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='Ciudad'),
        ),
    ]
