# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170210_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(None, 'G\xe9nero'), (1, 'Masculino'), (2, 'Femenino'), (99, 'Otro')], verbose_name='G\xe9nero'),
        ),
    ]
