# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Profile')),
                ('name_company', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la Empresa')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('responsability_iva', models.CharField(max_length=100, verbose_name='Responsabilidad ante el IVA')),
                ('sector_empresarial', models.CharField(blank=True, max_length=100, verbose_name='Sector empresarial')),
                ('workforce', models.IntegerField(default=0, verbose_name='Numero de Trabajadores')),
                ('tipology', models.CharField(choices=[('A', 'Empleador Directo'), ('B', 'Agencia de Reclutamiento'), ('C', 'Servicios Temporales')], max_length=100, verbose_name='Tipo de Empresa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion de la Empresa')),
                ('website', models.CharField(max_length=100, verbose_name='Sitio Web')),
                ('cuit', models.CharField(blank=True, max_length=255, null=True, verbose_name='CUIT')),
                ('reference', models.CharField(choices=[('A', 'Google '), ('B', 'Envio de Email'), ('C', 'Facebook'), ('C', 'Otros')], max_length=100, verbose_name='Referencia')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Noticias')),
                ('cv_spontany', models.BooleanField(default=False, verbose_name='CV espontaneos')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name_plural': 'Employers',
            },
            bases=('accounts.profile',),
        ),
    ]
