# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='name_company',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Empresa'),
        ),
    ]
