# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20160913_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='post_points',
            field=models.IntegerField(default=30, verbose_name='Puntos de publicaci\xf3n'),
        ),
    ]
