# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_employer_post_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Nueva'), (16, 'Aceptada'), (32, 'Rechazada')], default=0, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('readed_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_request_employer', to='employer.Employer', verbose_name='Empleador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_request_postulant', to=settings.AUTH_USER_MODEL, verbose_name='Postulante')),
            ],
        ),
    ]
