# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_cvtags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cvtags',
            unique_together=set([('employer', 'user')]),
        ),
    ]
