# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20170625_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='tipology',
            field=models.CharField(choices=[(None, 'Seleccione un elemento'), ('A', 'Empleador Directo'), ('B', 'Agencia de Reclutamiento'), ('C', 'Servicios Temporales')], max_length=100, verbose_name='Tipo de Empresa'),
        ),
    ]
