# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_language_userlanguages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Bachiller'), (2, 'T\xe9cnico'), (10, 'Pre-grado'), (11, 'Licenciatura'), (12, 'Master'), (13, 'Doctorado'), (14, 'Profesional'), (50, 'Honor'), (20, 'Certificaci\xf3n'), (99, 'Otro')], verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='Descripci\xf3n')),
                ('number_certification', models.CharField(blank=True, max_length=100, null=True, verbose_name='N\xfamero Certificado')),
                ('number_examen', models.CharField(blank=True, max_length=100, null=True, verbose_name='N\xfamero de Examen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='education.UserEducation', verbose_name='Adquirido en')),
            ],
        ),
    ]
