# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20170104_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='career',
            field=models.CharField(max_length=100, null=True, verbose_name='Carrera'),
        ),
    ]
