# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20190116_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
