# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('education', '0008_usereducation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Pa\xeds'),
        ),
    ]
