# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_usereducation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='usereducation',
            name='education_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education.EducationArea', verbose_name='\xc1rea de estudios'),
        ),
    ]
