# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-18 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0010_auto_20190116_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computerknowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserComputerknowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Niv\xe9l')),
                ('computerknowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Computerknowledge', verbose_name='Conocimiento Inform\xe1tico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computerknowledges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='educationarea',
            options={'verbose_name': '\xc1rea de estudio', 'verbose_name_plural': '\xc1reas de estudio'},
        ),
    ]
