# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-20 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0011_auto_20190118_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalknowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAdditionalknowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('additionalknowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Additionalknowledge', verbose_name='Conocimiento Adicional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalknowledges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
