# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-10 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0012_additionalknowledge_useradditionalknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkpreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpreferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workpreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userworkpreference',
            name='workpreference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Workpreference', verbose_name='Preferencia laboral'),
        ),
    ]
