# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepostulation',
            name='readed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
