# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170216_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='company',
            new_name='_company',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='company_logo',
            new_name='_company_logo',
        ),
    ]
