# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170228_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='course',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='course',
            name='currency_type',
            field=models.IntegerField(choices=[(1, 'Dolar USA'), (2, 'Euro'), (3, 'Peso Argentina')], default=1, verbose_name='Moneda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
