# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('reply_to', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('to', models.EmailField(max_length=254)),
                ('priority', models.SmallIntegerField(default=0)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_date', models.DateTimeField(default=None, null=True)),
                ('status', models.SmallIntegerField(default=None, null=True)),
                ('error', models.CharField(blank=True, default=None, max_length=8192, null=True)),
            ],
        ),
    ]
