# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailspool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='errors',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spool',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
