# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0028_auto_20170104_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_employer', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_job', to='jobs.Job')),
                ('postulant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_postulant', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_response', to='usermessages.UserMessage')),
            ],
        ),
    ]
