# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_job', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_response', to='usermessages.UserMessage'),
        ),
    ]
