# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0002_auto_20170127_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='readed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
