# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20170104_0744'),
        ('usermessages', '0003_auto_20170127_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='message_text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='job',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='postulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_postulation', to='jobs.JobPostulation'),
        ),
    ]
