# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_cvrequest'),
        ('usermessages', '0004_auto_20170205_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='cvrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_cv_request', to='employer.CVRequest'),
        ),
    ]
